name: 'Validate Images Changed'

description: 'Validates that the images are different from those generated previously'

inputs:
  image:
    description: 'Image'
    required: true

  previous_image:
    description: 'Previous image'
    required: true

runs:
  using: 'composite'
  steps:
  - id: validate
    shell: bash
    run: ${{ github.action_path }}/validate-images-changed
    env:
      IMAGE: ${{ inputs.image }}
      PREVIOUS_IMAGE: ${{ inputs.previous_image }}
